server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Send logs to the Loki service

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
  relabel_configs:
    # Use container name as job label
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: job
    # Use container ID as instance label
    - source_labels: ['__meta_docker_container_id']
      target_label: instance
    # Drop Promtail's own logs to prevent infinite loop
    - source_labels: ['job']
      regex: 'promtail'
      action: drop
    # Extract filename from the log path
    - source_labels: ['__meta_docker_log_path']
      regex: '.*(/.*\.log)'
      target_label: filename