apiVersion: 1

datasources:
  - name: Cassandra
    uid: cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    jsonData:
      keyspace: iot_data
      consistency: LOCAL_ONE
      timeout: 30
      tlsSkipVerify: true
      protocolVersion: 4
      username: ""
      password: ""

    isDefault: false
    editable: true
    version: 1
